In [9]:
from pyecharts import Bar

attr = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
v1 = [2.0, 4.9, 7.0, 23.2, 25.6, 76.7, 135.6, 162.2, 32.6, 20.0, 6.4, 3.3]
v2 = [2.6, 5.9, 9.0, 26.4, 28.7, 70.7, 175.6, 182.2, 48.7, 18.8, 6.0, 2.3]
bar = Bar("Bar chart", "precipitation and evaporation one year")
bar.add("precipitation", attr, v1, mark_line=["average"], mark_point=["max", "min"])
bar.add("evaporation", attr, v2, mark_line=["average"], mark_point=["max", "min"])
bar.render()

In [10]:
from pyecharts import Pie

In [6]:

bar = Bar('我的第一个图表','这里是副标题')
kwargs = dict(
    name = '柱形图',
    x_axis = ['衬衫','羊毛衫','雪纺衫','裤子','高跟鞋','袜子'],
    y_axis = [5,20,36,10,75,90]
)
bar.add(**kwargs)
bar.render('bar01.html')

In [7]:
bar

In [12]:
lf = pd.read_json('/Users/user/Desktop/tutorial-from-youtube/logfile.json')
lf.head()

  department  effect  evaluation  heard  importance username
0         it       8           5      1           5     bbbb
1   business       2           1      0           2     bbbb
2         it       1           3      0           2     bbbb
3         it       7           1      1           5     bbbb
4         it       2           2      1           4     bbbb

In [40]:
import pandas as pd
import numpy as np

In [150]:
df = pd.read_json('/Users/user/Desktop/Flask_Blog/flaskblog/static/faurecia.json')
df.head()

,Cycle time,Maximum injection pressure,Melt temperature,Mold wall temperature,Packing pressure,Packing time,Part weight,Quality,Sequence
0,"60,2402157584596","303,183269160703","204,775796004076","136,232090338703","96,2174429374479","2,03929257688295","300,225785600272",1,1
1,"59,7077040565916","316,45258726377","191,124392082044","144,106001162583","102,647633825739","1,93168410379266","283,555978441663",1,2
2,"59,4457038445446","300,434737228826","193,175360711396","132,707457243651","108,59073974678","1,92055905662103","287,78807175208",1,3
3,"61,651186181209","294,812475880438","212,447118991426","152,928157498737","100,313796790298","1,9492333715404","300,221216434511",1,4
4,"59,2462566309729","310,500184033095","218,771155102027","138,154297922142","96,9363796581796","1,90417361690823","310,570134060327",1,5

In [29]:
df.describe()

,Cycle_time,Maximum_injection_pressure,Melt_temperature,Mold_wall_temperature,Packing_pressure,Packing_time,Part_weight,Quality,Sequence
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.0,10000.000000,10000.000000,10000.00000
mean,60.015300,299.963200,200.031200,149.892700,100.033800,2.0,299.759500,0.992100,5000.50000
std,0.934534,8.595059,8.657847,8.485799,8.716379,0.0,9.248168,0.088535,2886.89568
min,58.000000,280.000000,180.000000,130.000000,80.000000,2.0,280.000000,0.000000,1.00000
25%,59.000000,294.000000,194.000000,144.000000,94.000000,2.0,293.000000,1.000000,2500.75000
50%,60.000000,300.000000,200.000000,150.000000,100.000000,2.0,300.000000,1.000000,5000.50000
75%,61.000000,306.000000,206.000000,156.000000,106.000000,2.0,306.000000,1.000000,7500.25000
max,62.000000,320.000000,220.000000,170.000000,120.000000,2.0,320.000000,1.000000,10000.00000

In [39]:
print("Correlation:", df.corr(method='pearson'))

Correlation:                             Cycle_time  Maximum_injection_pressure  \
Cycle_time                    1.000000                    0.007578
Maximum_injection_pressure    0.007578                    1.000000
Melt_temperature              0.004416                    0.017476
Mold_wall_temperature        -0.000197                    0.005572
Packing_pressure             -0.018689                   -0.000360
Packing_time                       NaN                         NaN
Part_weight                   0.005888                    0.018474
Quality                      -0.007000                    0.006846
Sequence                      0.017383                   -0.009554

                            Melt_temperature  Mold_wall_temperature  \
Cycle_time                          0.004416              -0.000197
Maximum_injection_pressure          0.017476               0.005572
Melt_temperature                    1.000000              -0.006027
Mold_wall_temperature              -0.006027               1.000000
Packing_pressure                   -0.003898               0.020567
Packing_time                             NaN                    NaN
Part_weight                         0.002636              -0.008914
Quality                            -0.011030              -0.017103
Sequence                            0.019785               0.006524

                            Packing_pressure  Packing_time  Part_weight  \
Cycle_time                         -0.018689           NaN     0.005888
Maximum_injection_pressure         -0.000360           NaN     0.018474
Melt_temperature                   -0.003898           NaN     0.002636
Mold_wall_temperature               0.020567           NaN    -0.008914
Packing_pressure                    1.000000           NaN     0.000840
Packing_time                             NaN           NaN          NaN
Part_weight                         0.000840           NaN     1.000000
Quality                             0.008899           NaN    -0.001099
Sequence                           -0.006536           NaN    -0.009764

                             Quality  Sequence
Cycle_time                 -0.007000  0.017383
Maximum_injection_pressure  0.006846 -0.009554
Melt_temperature           -0.011030  0.019785
Mold_wall_temperature      -0.017103  0.006524
Packing_pressure            0.008899 -0.006536
Packing_time                     NaN       NaN
Part_weight                -0.001099 -0.009764
Quality                     1.000000  0.024676
Sequence                    0.024676  1.000000

In [30]:
df['Cycle_time'].value_counts()

60    3992
61    2613
59    2486
62     461
58     448
Name: Cycle_time, dtype: int64

In [31]:
from pyecharts import Bar
from pyecharts import Pie
from pyecharts import configure
configure(global_theme='walden')

In [32]:
df['Cycle_time'].between(left=58, right=60).sum()

6926

In [ ]:
df['Cycle_time']

In [167]:
df = pd.read_json('/Users/user/Desktop/Flask_Blog/mockup.json')

In [168]:
df.head()

,Cycle_time,Maximum_injection_pressure,Melt_temperature,Mold_wall_temperature,Packing_pressure,Packing_time,Part_weight,Quality,Sequence
0,60,303,205,136,96,2,300,1,1
1,60,316,191,144,103,2,284,1,2
2,59,300,193,133,109,2,288,1,3
3,62,295,212,153,100,2,300,1,4
4,59,310,219,138,97,2,311,1,5

In [161]:
df.columns = ['Cycle_time', 'Maximum_injection_pressure','Melt_temperature', 'Mold_wall_temperature', 'Packing_pressure', 'Packing_time','Part_weight','Quality','Sequence']

In [162]:
df.info

<bound method DataFrame.info of             Cycle_time Maximum_injection_pressure  Melt_temperature  \
0     60,2402157584596           303,183269160703  204,775796004076
1     59,7077040565916            316,45258726377  191,124392082044
2     59,4457038445446           300,434737228826  193,175360711396
3      61,651186181209           294,812475880438  212,447118991426
4     59,2462566309729           310,500184033095  218,771155102027
5     59,4642641140136           300,120745326138  182,553725909692
6     60,4430859318736           302,284041683497   212,34047895371
7     58,1210721407364           308,851715446721    210,8922578067
8     60,9316404743656           297,045126681715  200,655211098141
9     59,4961867078728           304,835349636465  206,402828062524
10    61,1619440814908           308,815584522919  196,071022137872
11    59,3224648520144           291,172107310038  206,649205347868
12     59,153509948956           308,705359964108  207,283298254195
13    59,7731125203789           295,147733199525  207,799731110061
14    59,8947514764378           311,050739989496  190,990981410768
15    61,6576675655408           302,945500731098   203,63810237514
16    58,9984018905629           306,547555494563  188,801708928962
17    60,8280169400904           296,171665375861  199,847176868359
18    59,9057639697364           316,193779186795  216,587352273525
19    60,1101847895323           314,629779736562  207,202351709362
20    60,5013579297695           303,818336765623  204,407130301387
21    59,1563895341073           298,501397251023  190,398779736454
22    60,1125442483372           310,477476072042  195,802107139609
23    60,8353094727187           281,089280759323  198,132879931809
24    61,5489629127931           290,186346478904  194,679840537187
25    59,3319675499209           300,401633020697  199,567272942095
26    59,6712516933354           288,889653776085  199,240445426021
27    59,8457044800125            309,94155159676  202,822201532086
28    61,5889208460655           305,129305709546  199,404921926305
29    59,5410757008562            304,45420877946  203,142951495036
...                ...                        ...               ...
9970  60,1457101094415           304,434577083155  194,668752504661
9971  59,8131483518717           309,326261639012  202,121717050357
9972  60,3509247263251           300,312757167929  197,907986678158
9973    60,26437658711           292,921445765555  200,510100924377
9974  59,3736881112317           310,609310094159  212,498257651002
9975  61,0259069059895           299,657357332991  197,376879688937
9976  60,0208935693488           316,793286097077  211,632040542726
9977  59,1724914432952           296,071270930266  188,957467544691
9978  60,9766780649839           300,119838627012  213,918684755337
9979  59,3415489886352            288,40934909286  213,517211424641
9980  59,1820503528546            299,52266746119  211,345713497297
9981  60,0399357122973           292,268366686377  204,086387464923
9982  58,2398178225753           300,399187625694  208,055847279865
9983  60,6492661754985           313,363365491958  208,263424310224
9984  61,5376982437922           298,651529330582   200,75338888461
9985  61,7433963713134           302,608580159398  198,998490491518
9986  61,2071766565281           303,465705679798  191,877468761795
9987  59,6003302064617           296,592852893167  189,154375959413
9988  58,1742921442735           293,162542575315  195,354851306845
9989  58,6038111655443           303,644113717625  195,857783339386
9990  59,9569646736289           306,402320175858  196,605228094074
9991  60,6248673945444           310,769963331552  203,058403048177
9992  60,3435503997339           304,216864488558  200,321024272211
9993  59,6452085832536           297,397472079029  208,238161267496
9994  59,3234037332252           289,727941940422   185,20366316227
9995  59,9129005628923            292,97890028194  205,515374969416
9996  61,9181016373862           307,680969444054  187,462084624218
9997  61,1433233449563           308,631036504834   204,48493019812
9998  58,7181401420203           318,363275133604  192,842720118924
9999  60,4832217945815           311,552942018297  182,572509500051

     Mold_wall_temperature  Packing_pressure      Packing_time  \
0         136,232090338703  96,2174429374479  2,03929257688295
1         144,106001162583  102,647633825739  1,93168410379266
2         132,707457243651   108,59073974678  1,92055905662103
3         152,928157498737  100,313796790298   1,9492333715404
4         138,154297922142  96,9363796581796  1,90417361690823
5         149,608705492819  100,116552999292  2,05081725962158
6         147,360829277512  103,659209614771  1,96742181786854
7         164,006350375359  87,9914512611068  1,90226027688042
8         141,143373587468  92,8089047618897   2,0148395350572
9         152,314788767433  110,276310624719  2,05208319085824
10         163,32142806882  117,773974019747  2,02217928051174
11         151,30974773061  91,9442528619259  1,96781002708369
12        154,936546434574  117,787558621888  2,05688960535458
13        165,650981347949  91,8037530833377  1,99435571902622
14         153,77958241666  80,7521490754544  2,00415970126998
15        148,978882118991  90,3508553688969  2,08698371506826
16        145,684606833749  104,369775904142  2,08666146823662
17        157,475610286753   87,759882907763  2,08398447635396
18        145,641019448196   99,816128884739  1,95722681045502
19        149,875404617028   99,378342369895  2,04908038129325
20        141,633105691028   106,47141230885  1,92390029597597
21        154,760280357993  112,862301436766  1,93953145233418
22        149,667204808105   104,34176676589  2,01609276840624
23        134,605798491486  94,7937961040251  1,99697768102366
24        164,234067856889  94,3978928085133   1,9506539398716
25        149,704622417871  95,6964864307558    2,091952352255
26        169,991274193111  99,3889519010664   1,9710537021615
27        145,100494153888  92,7415235251662  1,98110669378162
28        159,774741636682  84,2712530009622  2,02105066619821
29        139,743155206387  98,1698599427215   2,0829063814382
...                    ...               ...               ...
9970      154,866313621246   111,62020374956  1,90557013095606
9971      155,285949332364   90,558012545739  2,09986361007852
9972      149,044511189208  118,952695035961  2,02358629530868
9973      148,794481386262  100,840771238613  2,08549935674871
9974      151,101871873291  90,3952173822594  2,03913404379767
9975      160,839920013323  83,3836876874193  2,04695047873514
9976      146,606269379778  89,3031010513782  2,04297603960326
9977      161,224698302815  110,224375004937  2,08185998811202
9978      143,940733151792  97,7522746390673  1,95554996920897
9979      162,036547392902  106,660443885065  2,03937165814374
9980      141,238259759816  86,3296804228252  1,99355006285165
9981      142,238911099164  96,9364331328154  1,91528692851345
9982      145,764858934833  101,276049418417  2,03612076965601
9983      145,896934845997  96,2736026051578  1,97547841201806
9984      140,164019976951  117,655863377456  1,93177071570024
9985      150,530795357799  98,5578217967644  1,97130848010073
9986      144,421137855628  104,306402238172  2,05560341727105
9987      159,078946883679  92,7965324717297  2,03210799970656
9988      168,661164329894   107,38632394057  1,97965869669419
9989      158,097100456413   117,14129889586   2,0447902731277
9990      149,243628958348  99,6809272706083  2,07007248296653
9991       144,27271044583  97,1051454906294  1,99519480285695
9992      149,488972314154  109,406217373374  1,94314168549973
9993      150,511182760404   108,59649199151  2,04907231597844
9994      161,447634946338  110,733232032835  1,99670553561224
9995      143,328945828417  100,829651078491  1,94598536760808
9996       152,22889802307  95,1407911700304   1,9800694919914
9997      160,338695831231  91,9377697417669  2,08939835987514
9998      151,049829395281  103,958171392048  1,90794258489936
9999      133,630735106449  106,891113788989  2,04269438743334

           Part_weight  Quality  Sequence
0     300,225785600272        1         1
1     283,555978441663        1         2
2      287,78807175208        1         3
3     300,221216434511        1         4
4     310,570134060327        1         5
5     308,616095834001        1         6
6     294,686682333968        1         7
7     295,921876902624        1         8
8     299,122393629644        1         9
9     316,844172900723        1        10
10    282,672915214799        1        11
11    307,060025267259        1        12
12    306,865079708913        1        13
13     317,60874495198        1        14
14    308,477638775883        1        15
15    317,024226728207        1        16
16    294,141845922733        1        17
17    298,656208578429        1        18
18    301,664936008605        1        19
19    300,349854660869        1        20
20    301,544636331954        1        21
21    313,602039684877        1        22
22    303,048538012228        1        23
23    302,543644138436        1        24
24    310,602434284116        1        25
25    306,485094106305        1        26
26    305,078109569981        1        27
27    299,031073472629        1        28
28    300,178956127813        1        29
29      294,3680539662        1        30
...                ...      ...       ...
9970  313,271306370418        1      9971
9971  287,694113912056        1      9972
9972  291,027925297889        1      9973
9973  300,881760247409        1      9974
9974  286,655974786881        1      9975
9975  304,493961217769        1      9976
9976  281,497153085609        1      9977
9977  319,677469148211        1      9978
9978  290,234300934285        1      9979
9979  298,173511988205        1      9980
9980  312,023774114624        1      9981
9981  297,832670455473        1      9982
9982  299,627418793956        1      9983
9983  300,739606633111        1      9984
9984  302,529487847537        1      9985
9985  295,932824587573        1      9986
9986  286,783403352369        1      9987
9987  314,034261670201        1      9988
9988  299,856748464444        1      9989
9989  313,706058904237        1      9990
9990  304,788461044952        1      9991
9991   291,54099333353        1      9992
9992  286,723266970112        1      9993
9993  310,545671149681        1      9994
9994  296,177243357463        1      9995
9995   311,29351251448        1      9996
9996  317,116363995215        1      9997
9997  298,792023354371        1      9998
9998  283,827260159085        1      9999
9999  308,597357874064        1     10000

[10000 rows x 9 columns]>

In [61]:
df.head()

,Cycle_time,Maximum_injection_pressure,Melt_temperature,Mold_wall_temperature,Packing_pressure,Packing_time,Part_weight,Quality,Sequence
0,"60,2402157584596","303,183269160703","204,775796004076","136,232090338703","96,2174429374479","2,03929257688295","300,225785600272",1,1
1,"59,7077040565916","316,45258726377","191,124392082044","144,106001162583","102,647633825739","1,93168410379266","283,555978441663",1,2
2,"59,4457038445446","300,434737228826","193,175360711396","132,707457243651","108,59073974678","1,92055905662103","287,78807175208",1,3
3,"61,651186181209","294,812475880438","212,447118991426","152,928157498737","100,313796790298","1,9492333715404","300,221216434511",1,4
4,"59,2462566309729","310,500184033095","218,771155102027","138,154297922142","96,9363796581796","1,90417361690823","310,570134060327",1,5

In [163]:
df['Maximum_injection_pressure'] = df['Maximum_injection_pressure'].map(lambda x:x.replace(',', '.') if ',' in x else x)
df['Melt_temperature'] = df['Melt_temperature'].map(lambda x:x.replace(',', '.') if ',' in x else x)
df['Mold_wall_temperature'] = df['Mold_wall_temperature'].map(lambda x:x.replace(',', '.') if ',' in x else x)
df['Packing_pressure'] = df['Packing_pressure'].map(lambda x:x.replace(',', '.') if ',' in x else x)
df['Packing_time'] = df['Packing_time'].map(lambda x:x.replace(',', '.') if ',' in x else x)
df['Part_weight'] = df['Part_weight'].map(lambda x:x.replace(',', '.') if ',' in x else x)
df['Cycle_time'] = df['Cycle_time'].map(lambda x:x.replace(',', '.') if ',' in x else x)

In [164]:
df.head()

,Cycle_time,Maximum_injection_pressure,Melt_temperature,Mold_wall_temperature,Packing_pressure,Packing_time,Part_weight,Quality,Sequence
0,60.2402157584596,303.183269160703,204.775796004076,136.232090338703,96.2174429374479,2.03929257688295,300.225785600272,1,1
1,59.7077040565916,316.45258726377,191.124392082044,144.106001162583,102.647633825739,1.93168410379266,283.555978441663,1,2
2,59.4457038445446,300.434737228826,193.175360711396,132.707457243651,108.59073974678,1.92055905662103,287.78807175208,1,3
3,61.651186181209,294.812475880438,212.447118991426,152.928157498737,100.313796790298,1.9492333715404,300.221216434511,1,4
4,59.2462566309729,310.500184033095,218.771155102027,138.154297922142,96.9363796581796,1.90417361690823,310.570134060327,1,5

In [169]:
df = df.to_csv('/Users/user/Desktop/Flask_Blog/aaa.csv')

In [74]:
df = df.round(0)

In [75]:
df.head()

,Cycle_time,Maximum_injection_pressure,Melt_temperature,Mold_wall_temperature,Packing_pressure,Packing_time,Part_weight,Quality,Sequence
0,60.2402157584596,303.183269160703,204.775796004076,136.232090338703,96.2174429374479,2.03929257688295,300.225785600272,1,1
1,59.7077040565916,316.45258726377,191.124392082044,144.106001162583,102.647633825739,1.93168410379266,283.555978441663,1,2
2,59.4457038445446,300.434737228826,193.175360711396,132.707457243651,108.59073974678,1.92055905662103,287.78807175208,1,3
3,61.651186181209,294.812475880438,212.447118991426,152.928157498737,100.313796790298,1.9492333715404,300.221216434511,1,4
4,59.2462566309729,310.500184033095,218.771155102027,138.154297922142,96.9363796581796,1.90417361690823,310.570134060327,1,5

In [76]:
df = df.apply(lambda x:x.replace('.0', '') if '.0' in x else x)

In [77]:
df.tail()

,Cycle_time,Maximum_injection_pressure,Melt_temperature,Mold_wall_temperature,Packing_pressure,Packing_time,Part_weight,Quality,Sequence
9995,59.9129005628923,292.97890028194,205.515374969416,143.328945828417,100.829651078491,1.94598536760808,311.29351251448,1,9996
9996,61.9181016373862,307.680969444054,187.462084624218,152.22889802307,95.1407911700304,1.9800694919914,317.116363995215,1,9997
9997,61.1433233449563,308.631036504834,204.48493019812,160.338695831231,91.9377697417669,2.08939835987514,298.792023354371,1,9998
9998,58.7181401420203,318.363275133604,192.842720118924,151.049829395281,103.958171392048,1.90794258489936,283.827260159085,1,9999
9999,60.4832217945815,311.552942018297,182.572509500051,133.630735106449,106.891113788989,2.04269438743334,308.597357874064,1,10000

In [41]:
df.to_json('mockup.json', orient='records')

In [42]:
df.head()

,Cycle_time,Maximum_injection_pressure,Melt_temperature,Mold_wall_temperature,Packing_pressure,Packing_time,Part_weight,Quality,Sequence
0,60.0,303.0,205.0,136.0,96.0,2.0,300.0,1,1
1,60.0,316.0,191.0,144.0,103.0,2.0,284.0,1,2
2,59.0,300.0,193.0,133.0,109.0,2.0,288.0,1,3
3,62.0,295.0,212.0,153.0,100.0,2.0,300.0,1,4
4,59.0,310.0,219.0,138.0,97.0,2.0,311.0,1,5

In [17]:
nb_sequence = df.describe()['Sequence']['count']

In [18]:
nb_sequence

10000.0

In [19]:
df.dtypes

Cycle_time                    object
Maximum_injection_pressure    object
Melt_temperature              object
Mold_wall_temperature         object
Packing_pressure              object
Packing_time                  object
Part_weight                   object
Quality                        int64
Sequence                       int64
dtype: object

In [20]:
cols = df.select_dtypes(exclude=['float'] and ['int']).columns

In [21]:
df[cols] = df[cols].apply(pd.to_numeric, downcast='float', errors='coerce')

In [22]:
df.dtypes

Cycle_time                    float32
Maximum_injection_pressure    float32
Melt_temperature              float32
Mold_wall_temperature         float32
Packing_pressure              float32
Packing_time                  float32
Part_weight                   float32
Quality                         int64
Sequence                        int64
dtype: object

In [24]:
df = df.round(2)

In [25]:
df.head()

,Cycle_time,Maximum_injection_pressure,Melt_temperature,Mold_wall_temperature,Packing_pressure,Packing_time,Part_weight,Quality,Sequence
0,60.240002,303.179993,204.779999,136.229996,96.220001,2.04,300.230011,1,1
1,59.709999,316.450012,191.119995,144.110001,102.650002,1.93,283.559998,1,2
2,59.450001,300.429993,193.179993,132.710007,108.589996,1.92,287.790009,1,3
3,61.650002,294.809998,212.449997,152.929993,100.309998,1.95,300.220001,1,4
4,59.250000,310.500000,218.770004,138.149994,96.940002,1.90,310.570007,1,5

In [26]:
avg_cycle = df.describe()['Cycle_time']['mean']

In [27]:
avg_cycle

60.0138053894043

In [28]:
df.describe()

,Cycle_time,Maximum_injection_pressure,Melt_temperature,Mold_wall_temperature,Packing_pressure,Packing_time,Part_weight,Quality,Sequence
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000
mean,60.013805,299.959625,200.028839,149.890793,100.035370,2.000410,299.759399,0.992100,5000.50000
std,0.875639,8.594129,8.653775,8.486456,8.708156,0.057937,9.238999,0.088535,2886.89568
min,58.000000,280.000000,180.009995,130.009995,80.000000,1.900000,280.010010,0.000000,1.00000
25%,59.369999,293.929993,193.949997,143.910004,93.910004,1.950000,293.390015,1.000000,2500.75000
50%,60.020000,299.970001,200.059998,149.885002,99.989998,2.000000,299.980011,1.000000,5000.50000
75%,60.669998,306.059998,206.320007,155.679993,106.192501,2.050000,305.989990,1.000000,7500.25000
max,61.990002,319.989990,219.990005,169.990005,119.970001,2.100000,320.000000,1.000000,10000.00000

In [29]:
data = df.loc[df['Quality'] == 0]

In [30]:
data.head()

,Cycle_time,Maximum_injection_pressure,Melt_temperature,Mold_wall_temperature,Packing_pressure,Packing_time,Part_weight,Quality,Sequence
30,59.169998,300.559998,196.350006,149.789993,95.809998,2.09,302.480011,0,31
410,61.430000,297.500000,186.479996,138.009995,95.730003,2.09,299.420013,0,411
494,60.610001,289.480011,216.550003,148.070007,97.360001,2.07,299.600006,0,495
547,60.740002,307.459991,208.119995,146.059998,113.449997,1.92,290.609985,0,548
554,61.689999,292.299988,199.720001,148.000000,86.400002,2.08,316.549988,0,555

In [79]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 79 entries, 30 to 9704
Data columns (total 9 columns):
Cycle_time                    79 non-null float32
Maximum_injection_pressure    79 non-null float32
Melt_temperature              79 non-null float32
Mold_wall_temperature         79 non-null float32
Packing_pressure              79 non-null float32
Packing_time                  79 non-null float32
Part_weight                   79 non-null float32
Quality                       79 non-null int64
Sequence                      79 non-null int64
dtypes: float32(7), int64(2)
memory usage: 6.5 KB

In [93]:
data = data.round(0)

In [91]:
data = pd.read_json('/Users/user/Desktop/Flask_Blog/noQuality.json')

In [112]:
data.tail()

,Cycle_time,Maximum_injection_pressure,Melt_temperature,Mold_wall_temperature,Packing_pressure,Packing_time,Part_weight,Quality,Sequence
74,60,300,219,158,114,2,303,0,9021
75,60,301,193,149,97,2,298,0,9611
76,59,298,185,142,83,2,300,0,9644
77,60,301,204,155,100,2,291,0,9692
78,61,294,219,153,99,2,303,0,9705

In [113]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79 entries, 0 to 78
Data columns (total 9 columns):
Cycle_time                    79 non-null int64
Maximum_injection_pressure    79 non-null int64
Melt_temperature              79 non-null int64
Mold_wall_temperature         79 non-null int64
Packing_pressure              79 non-null int64
Packing_time                  79 non-null int64
Part_weight                   79 non-null int64
Quality                       79 non-null int64
Sequence                      79 non-null int64
dtypes: int64(9)
memory usage: 5.6 KB

In [101]:
data.to_json('/Users/user/Desktop/Flask_Blog/noQuality.json', orient='records')

In [119]:
df = pd.read_json('/Users/user/Desktop/Flask_Blog/mockup.json')

In [117]:
dataGood = df.loc[df['Quality'] == 1]

In [118]:
dataGood = dataGood.sample(n=100)

In [121]:
dataGood.head()

,Cycle_time,Maximum_injection_pressure,Melt_temperature,Mold_wall_temperature,Packing_pressure,Packing_time,Part_weight,Quality,Sequence
9790,60,301,187,151,88,2,292,1,9791
4142,59,287,192,164,101,2,303,1,4143
9200,59,302,199,146,93,2,310,1,9201
7160,61,313,190,154,96,2,314,1,7161
7363,60,307,205,154,86,2,310,1,7364

In [122]:
dataGood.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 100 entries, 9790 to 7367
Data columns (total 9 columns):
Cycle_time                    100 non-null int64
Maximum_injection_pressure    100 non-null int64
Melt_temperature              100 non-null int64
Mold_wall_temperature         100 non-null int64
Packing_pressure              100 non-null int64
Packing_time                  100 non-null int64
Part_weight                   100 non-null int64
Quality                       100 non-null int64
Sequence                      100 non-null int64
dtypes: int64(9)
memory usage: 7.8 KB

In [123]:
dataGood.to_json('quality.json', orient='records')

In [140]:
df = pd.read_json('/Users/user/Desktop/Flask_Blog/noQuality.json')

In [146]:
def example(a, b, c, d, e ):
     if arg1 == 1 and arg2 == 2 and arg3 == 3:
          print("Example Text")

In [147]:
example(1,2,3)

Example Text

In [45]:
df['Cycle_time'].value_counts()

60    33
61    25
59    16
58     3
62     2
Name: Cycle_time, dtype: int64

In [51]:
ranges = [0,58,61,62]

In [52]:
df.groupby(pd.cut(df.Cycle_time, ranges)).count()

,Cycle_time,Maximum_injection_pressure,Melt_temperature,Mold_wall_temperature,Packing_pressure,Packing_time,Part_weight,Quality,Sequence
Cycle_time,,,,,,,,,
"(0, 58]",3,3,3,3,3,3,3,3,3
"(58, 61]",74,74,74,74,74,74,74,74,74
"(61, 62]",2,2,2,2,2,2,2,2,2

In [63]:
cycle = 74/79 #accept 58-61

In [64]:
print(cycle)

0.9367088607594937

In [60]:
ranges = [0,280,290,300,310,320]

In [61]:
df.groupby(pd.cut(df.Maximum_injection_pressure, ranges)).count()

,Cycle_time,Maximum_injection_pressure,Melt_temperature,Mold_wall_temperature,Packing_pressure,Packing_time,Part_weight,Quality,Sequence
Maximum_injection_pressure,,,,,,,,,
"(0, 280]",1,1,1,1,1,1,1,1,1
"(280, 290]",14,14,14,14,14,14,14,14,14
"(290, 300]",30,30,30,30,30,30,30,30,30
"(300, 310]",24,24,24,24,24,24,24,24,24
"(310, 320]",10,10,10,10,10,10,10,10,10

In [71]:
inject = (14+30+24)/df.Maximum_injection_pressure.size

In [72]:
print(inject) #accept 280-310

0.8607594936708861

In [77]:
ranges = [0,180,190,200,210,220,230]

In [78]:
df.groupby(pd.cut(df.Melt_temperature, ranges)).count()

,Cycle_time,Maximum_injection_pressure,Melt_temperature,Mold_wall_temperature,Packing_pressure,Packing_time,Part_weight,Quality,Sequence
Melt_temperature,,,,,,,,,
"(0, 180]",0,0,0,0,0,0,0,0,0
"(180, 190]",12,12,12,12,12,12,12,12,12
"(190, 200]",27,27,27,27,27,27,27,27,27
"(200, 210]",27,27,27,27,27,27,27,27,27
"(210, 220]",13,13,13,13,13,13,13,13,13
"(220, 230]",0,0,0,0,0,0,0,0,0

In [79]:
melt = (27+27+13)/df.Melt_temperature.size # accept 190 - 220
print(melt)

0.8481012658227848

In [81]:
#df['Mold_wall_temperature'].value_counts()

In [85]:
df[(df['Mold_wall_temperature'] >= 160)].count()

Cycle_time                    12
Maximum_injection_pressure    12
Melt_temperature              12
Mold_wall_temperature         12
Packing_pressure              12
Packing_time                  12
Part_weight                   12
Quality                       12
Sequence                      12
dtype: int64

In [86]:
mold = (79-12)/79 #accept 130-160
print(melt)

0.8481012658227848

In [87]:
weight_groups = pd.cut(df['Part_weight'], bins=[0,280,290,300,310,320])

In [93]:
ranges =[0,280,290,300,310,320]
df.groupby(pd.cut(df.Part_weight, ranges)).count()

,Cycle_time,Maximum_injection_pressure,Melt_temperature,Mold_wall_temperature,Packing_pressure,Packing_time,Part_weight,Quality,Sequence
Part_weight,,,,,,,,,
"(0, 280]",0,0,0,0,0,0,0,0,0
"(280, 290]",13,13,13,13,13,13,13,13,13
"(290, 300]",30,30,30,30,30,30,30,30,30
"(300, 310]",27,27,27,27,27,27,27,27,27
"(310, 320]",9,9,9,9,9,9,9,9,9

In [94]:
weight = (79-9)/79 #accept 280-310
print(weight)

0.8860759493670886

In [101]:
def count_values_in_range(series, range_min, range_max):

    # "between" returns a boolean Series equivalent to left <= series <= right.
    # NA values will be treated as False.
    return series.between(left=range_min, right=range_max).sum()
pack_pressure = (df.Packing_pressure.between(80,110).sum())/df.Packing_pressure.size
print(pack_pressure) #accept 80-110

0.8987341772151899

In [104]:
df.groupby(["Cycle_time", "Packing_time"]).size()

Cycle_time  Packing_time
58          2                3
59          2               16
60          2               33
61          2               25
62          2                2
dtype: int64

In [117]:
df = df.groupby(["Maximum_injection_pressure", "Packing_pressure"])

In [127]:
df["Quality"][(df["Maximum_injection_pressure"] > 310) & (df["Packing_pressure"] > 110)].count()

1